#!/usr/bin/env bash
#
# Claude Agent Bootstrap v3 — any repo, any language, any model setup.
# Usage: ~/claude-agent-bootstrap/setup.sh [--defaults]
#
# Run from your project root. Generates:
#   - CLAUDE.md (agent instructions, appended to existing)
#   - LOOPS.md (loop documentation + manual paste commands)
#   - .claude/settings.json (autonomous permissions)
#   - .claude/loops/*.txt (individual loop prompt files)
#   - .claude/bootstrap.conf (saved config)
#   - start-loops.sh (tmux launcher)
#   - .github/workflows/ci.yml (if applicable)
#
# Supports: Node.js, Python, Go, Rust, and generic projects
# Models: Dual (Sonnet+Opus), Single Sonnet, or Single Opus
#
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"
# ─── Parse arguments ─────────────────────────────────────────────────
USE_DEFAULTS=false
for arg in "$@"; do
  case "$arg" in
    --defaults) USE_DEFAULTS=true ;;
  esac
done

# ─── Detect project ──────────────────────────────────────────────────
REPO_NAME=$(basename "$REPO_ROOT")
ORIGIN_URL=$(git remote get-url origin 2>/dev/null || echo "")
GITHUB_USER=$(echo "$ORIGIN_URL" | sed -n 's|.*github.com[:/]\([^/]*\)/.*|\1|p')
GITHUB_REPO=$(echo "$ORIGIN_URL" | sed -n 's|.*github.com[:/][^/]*/\(.*\)\.git|\1|p')

if [[ -z "${GITHUB_REPO:-}" ]]; then
  GITHUB_REPO=$(echo "$ORIGIN_URL" | sed -n 's|.*github.com[:/][^/]*/\(.*\)|\1|p')
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Claude Agent Bootstrap v3"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Project: $REPO_NAME"
echo "GitHub:  ${GITHUB_USER:-unknown}/${GITHUB_REPO:-unknown}"

if [[ -z "${GITHUB_USER:-}" ]] || [[ -z "${GITHUB_REPO:-}" ]]; then
  echo ""
  echo "WARNING: Could not detect GitHub remote. Agent loops need it."
  echo "  Set up with: git remote add origin https://github.com/<user>/<repo>.git"
  echo "  Then re-run this script."
fi
# ─── Interactive config ──────────────────────────────────────────────
BOOTSTRAP_CONF=".claude/bootstrap.conf"
mkdir -p .claude

if [[ -f "$BOOTSTRAP_CONF" ]]; then
  echo ""
  echo "Using saved config from $BOOTSTRAP_CONF"
  source "$BOOTSTRAP_CONF"
elif [[ "$USE_DEFAULTS" == "true" ]] || [[ ! -t 0 ]]; then
  MODEL_MODE="single-sonnet"
  AUTO_LABELS="true"
  LOOP_SPEED="normal"
  echo ""
  echo "Using defaults: single-sonnet, auto-labels, normal speed"
else
  echo ""
  echo "? Model mode:"
  echo "  [1] Dual (Sonnet+Opus) — 2 sessions, 7 loops"
  echo "  [2] Sonnet only — 1 session, 5 loops (recommended to start)"
  echo "  [3] Opus only — 1 session, 5 loops"
  read -rp "  Choice [2]: " mode_choice
  case "${mode_choice:-2}" in
    1) MODEL_MODE="dual" ;;
    3) MODEL_MODE="single-opus" ;;
    *) MODEL_MODE="single-sonnet" ;;
  esac

  read -rp "? Auto-create GitHub labels? [Y/n]: " label_choice
  case "${label_choice:-Y}" in
    [nN]*) AUTO_LABELS="false" ;;
    *) AUTO_LABELS="true" ;;
  esac

  echo "? Loop speed:"
  echo "  [1] Fast (2m/5m) — aggressive, higher API cost"
  echo "  [2] Normal (5m/15m) — balanced"
  echo "  [3] Relaxed (10m/30m) — conservative, lower cost"
  read -rp "  Choice [2]: " speed_choice
  case "${speed_choice:-2}" in
    1) LOOP_SPEED="fast" ;;
    3) LOOP_SPEED="relaxed" ;;
    *) LOOP_SPEED="normal" ;;
  esac
fi

# Save config
cat > "$BOOTSTRAP_CONF" << CONF_EOF
# Claude Agent Bootstrap config — generated by setup.sh v3
MODEL_MODE="$MODEL_MODE"
AUTO_LABELS="$AUTO_LABELS"
LOOP_SPEED="$LOOP_SPEED"
CONF_EOF

echo "  Mode: $MODEL_MODE | Labels: $AUTO_LABELS | Speed: $LOOP_SPEED"

# ─── Map speed to intervals ─────────────────────────────────────────
case "$LOOP_SPEED" in
  fast)
    TRIAGE_INTERVAL="2m"; WORKER_INTERVAL="5m"; RESPONDER_INTERVAL="2m"
    MAINTENANCE_INTERVAL="30m"; SWEEP_INTERVAL="1h"
    ;;
  relaxed)
    TRIAGE_INTERVAL="10m"; WORKER_INTERVAL="30m"; RESPONDER_INTERVAL="10m"
    MAINTENANCE_INTERVAL="2h"; SWEEP_INTERVAL="4h"
    ;;
  *) # normal
    TRIAGE_INTERVAL="5m"; WORKER_INTERVAL="15m"; RESPONDER_INTERVAL="5m"
    MAINTENANCE_INTERVAL="1h"; SWEEP_INTERVAL="2h"
    ;;
esac
# ─── Multi-language detection ────────────────────────────────────────
LANG_TYPE="generic"
PKG_DIR=""
PKG_MGR=""
SRC_DIR=""
INSTALL_CMD=""
LINT_CMD=""
LINT_FIX_CMD=""
BUILD_CMD=""
TEST_CMD=""

# Detect in priority order
if [[ -f "package.json" ]]; then LANG_TYPE="node"; PKG_DIR="."
elif [[ -f "web/package.json" ]]; then LANG_TYPE="node"; PKG_DIR="web"
elif [[ -f "app/package.json" ]]; then LANG_TYPE="node"; PKG_DIR="app"
elif [[ -f "frontend/package.json" ]]; then LANG_TYPE="node"; PKG_DIR="frontend"
elif [[ -f "pyproject.toml" ]] || [[ -f "requirements.txt" ]]; then LANG_TYPE="python"
elif [[ -f "go.mod" ]]; then LANG_TYPE="go"
elif [[ -f "Cargo.toml" ]]; then LANG_TYPE="rust"
fi

case "$LANG_TYPE" in
  node)
    # Package manager
    if [[ -f "$PKG_DIR/bun.lockb" ]]; then PKG_MGR="bun"
    elif [[ -f "$PKG_DIR/pnpm-lock.yaml" ]]; then PKG_MGR="pnpm"
    elif [[ -f "$PKG_DIR/yarn.lock" ]]; then PKG_MGR="yarn"
    else PKG_MGR="npm"; fi

    # Install
    if [[ "$PKG_MGR" == "npm" ]]; then INSTALL_CMD="cd $PKG_DIR && npm ci"
    else INSTALL_CMD="cd $PKG_DIR && $PKG_MGR install"; fi

    # Source directory
    if [[ -d "$PKG_DIR/src" ]]; then SRC_DIR="$PKG_DIR/src"
    elif [[ -d "$PKG_DIR/app" ]]; then SRC_DIR="$PKG_DIR/app"
    elif [[ -d "$PKG_DIR/lib" ]]; then SRC_DIR="$PKG_DIR/lib"
    else SRC_DIR="$PKG_DIR"; fi

    # Detect npm scripts (no python3 dependency)
    SCRIPTS=""
    if command -v node &>/dev/null; then
      SCRIPTS=$(node -e "try{const p=require('./$PKG_DIR/package.json');console.log(Object.keys(p.scripts||{}).join(' '))}catch(e){}" 2>/dev/null || echo "")
    fi
    if [[ -z "$SCRIPTS" ]]; then
      SCRIPTS=$(grep -oE '"(lint|build|test|dev|start|typecheck)"' "$PKG_DIR/package.json" 2>/dev/null | tr -d '"' | tr '\n' ' ' || echo "")
    fi

    [[ "$SCRIPTS" == *"lint"* ]] && LINT_CMD="cd $PKG_DIR && $PKG_MGR run lint"
    [[ "$SCRIPTS" == *"build"* ]] && BUILD_CMD="cd $PKG_DIR && $PKG_MGR run build"
    [[ "$SCRIPTS" == *"test"* ]] && TEST_CMD="cd $PKG_DIR && $PKG_MGR test"

    # Vitest fallback
    if [[ -z "$TEST_CMD" ]] && grep -q "vitest" "$PKG_DIR/package.json" 2>/dev/null; then
      TEST_CMD="cd $PKG_DIR && npx vitest run"
    fi

    # Lint fix
    if [[ -n "$LINT_CMD" ]]; then LINT_FIX_CMD="$LINT_CMD --fix"
    else LINT_FIX_CMD="cd $PKG_DIR && npx eslint ${SRC_DIR} --fix"; fi
    ;;

  python)
    if [[ -f "pyproject.toml" ]]; then INSTALL_CMD="pip install -e ."
    else INSTALL_CMD="pip install -r requirements.txt"; fi

    if [[ -d "src" ]]; then SRC_DIR="src"; else SRC_DIR="."; fi

    LINT_CMD="ruff check ."
    LINT_FIX_CMD="ruff check --fix ."
    TEST_CMD="pytest"
    ;;

  go)
    INSTALL_CMD="go mod download"
    SRC_DIR="."

    if [[ -f ".golangci.yml" ]] || [[ -f ".golangci.yaml" ]]; then
      LINT_CMD="golangci-lint run ./..."
      LINT_FIX_CMD="golangci-lint run --fix ./..."
    else
      LINT_CMD="go vet ./..."
      LINT_FIX_CMD=""
    fi

    BUILD_CMD="go build ./..."
    TEST_CMD="go test ./..."
    ;;

  rust)
    SRC_DIR="src"
    LINT_CMD="cargo clippy"
    LINT_FIX_CMD="cargo clippy --fix --allow-dirty"
    BUILD_CMD="cargo build"
    TEST_CMD="cargo test"
    ;;

  generic)
    SRC_DIR="."
    ;;
esac

echo ""
echo "Language: $LANG_TYPE"
[[ -n "$PKG_DIR" ]] && echo "Package dir: $PKG_DIR"
[[ -n "$PKG_MGR" ]] && echo "Package manager: $PKG_MGR"
echo "Source dir: ${SRC_DIR:-.}"
echo "Commands:"
echo "  install: ${INSTALL_CMD:-none}"
echo "  lint:    ${LINT_CMD:-none}"
echo "  build:   ${BUILD_CMD:-none}"
echo "  test:    ${TEST_CMD:-none}"

# ─── Build verify chain ──────────────────────────────────────────────
VERIFY_CHAIN=""
[[ -n "$INSTALL_CMD" ]] && VERIFY_CHAIN="$INSTALL_CMD"
[[ -n "$LINT_CMD" ]] && VERIFY_CHAIN="${VERIFY_CHAIN:+$VERIFY_CHAIN && }$LINT_CMD"
[[ -n "$BUILD_CMD" ]] && VERIFY_CHAIN="${VERIFY_CHAIN:+$VERIFY_CHAIN && }$BUILD_CMD"
[[ -n "$TEST_CMD" ]] && VERIFY_CHAIN="${VERIFY_CHAIN:+$VERIFY_CHAIN && }$TEST_CMD"

# ─── Model configuration ─────────────────────────────────────────────
SINGLE_MODEL=""
SINGLE_MODEL_NAME=""
case "$MODEL_MODE" in
  single-opus)  SINGLE_MODEL="claude-opus-4-6"; SINGLE_MODEL_NAME="Opus" ;;
  single-sonnet) SINGLE_MODEL="claude-sonnet-4-6"; SINGLE_MODEL_NAME="Sonnet" ;;
esac
# ─── MCP preflight check ─────────────────────────────────────────────
echo ""
MCP_OK=false
if [[ -f "$HOME/.claude.json" ]] && grep -q '"github"' "$HOME/.claude.json" 2>/dev/null; then
  MCP_OK=true
  echo "GitHub MCP server detected"
fi

if [[ "$MCP_OK" == "false" ]]; then
  echo "WARNING: GitHub MCP server not detected. The agent loops require it."
  echo "  Run this to configure it:"
  echo "    claude mcp add github -- npx -y @modelcontextprotocol/server-github"
  echo "  Then set GITHUB_PERSONAL_ACCESS_TOKEN in your environment."
  echo ""
  if [[ -t 0 ]] && [[ "$USE_DEFAULTS" == "false" ]]; then
    read -rp "  Continue anyway? [y/N]: " mcp_choice
    case "${mcp_choice:-N}" in
      [yY]*) echo "  Continuing (loops will fail without GitHub MCP)" ;;
      *) echo "  Aborting. Configure GitHub MCP and re-run."; exit 1 ;;
    esac
  else
    echo "  Continuing without GitHub MCP (configure before starting loops)"
  fi
fi

echo ""

# ─── Create .claude/settings.json ────────────────────────────────────
cat > .claude/settings.json << 'SETTINGS_EOF'
{
  "permissions": {
    "allow": [
      "Bash",
      "Edit",
      "Read",
      "Write",
      "Glob",
      "Grep",
      "Agent",
      "WebSearch",
      "WebFetch",
      "mcp__*"
    ],
    "deny": [
      "Bash(rm -rf /)*",
      "Bash(npm publish*)",
      "Bash(cargo publish*)",
      "Bash(pip upload*)",
      "Bash(twine upload*)"
    ]
  }
}
SETTINGS_EOF
echo "Created .claude/settings.json"
# ─── Create CI workflow ───────────────────────────────────────────────
if [[ -f ".github/workflows/ci.yml" ]]; then
  echo "ci.yml already exists, skipping"
elif [[ "$LANG_TYPE" == "generic" ]]; then
  echo "Skipping CI (generic project — configure manually if needed)"
else
  mkdir -p .github/workflows

  case "$LANG_TYPE" in
    node)
      # Detect cache settings
      CACHE_MGR="npm"
      CACHE_DEP_PATH="$PKG_DIR/package-lock.json"
      if [[ "$PKG_MGR" == "yarn" ]]; then
        CACHE_MGR="yarn"; CACHE_DEP_PATH="$PKG_DIR/yarn.lock"
      elif [[ "$PKG_MGR" == "pnpm" ]]; then
        CACHE_MGR="pnpm"; CACHE_DEP_PATH="$PKG_DIR/pnpm-lock.yaml"
      elif [[ "$PKG_MGR" == "bun" ]]; then
        CACHE_MGR=""; CACHE_DEP_PATH=""
      fi

      IS_NEXTJS=""
      if grep -q '"next"' "$PKG_DIR/package.json" 2>/dev/null; then
        IS_NEXTJS="true"
      fi

      # Build CI steps dynamically
      CI_STEPS=""
      [[ -n "$INSTALL_CMD" ]] && CI_STEPS="${CI_STEPS}      - run: $INSTALL_CMD
"
      [[ -n "$LINT_CMD" ]] && CI_STEPS="${CI_STEPS}      - run: $LINT_CMD
"
      if [[ -n "$BUILD_CMD" ]]; then
        if [[ -n "$IS_NEXTJS" ]]; then
          CI_STEPS="${CI_STEPS}      - run: $BUILD_CMD
        # Add NEXT_PUBLIC_* env vars if your build needs them:
        # env:
        #   NEXT_PUBLIC_API_URL: \${{ secrets.NEXT_PUBLIC_API_URL }}
"
        else
          CI_STEPS="${CI_STEPS}      - run: $BUILD_CMD
"
        fi
      fi
      if [[ -n "$TEST_CMD" ]]; then
        CI_STEPS="${CI_STEPS}      - name: Run tests
        run: $TEST_CMD
        continue-on-error: true
"
      fi

      cat > .github/workflows/ci.yml << CI_EOF
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
$(if [[ -n "$CACHE_MGR" ]]; then
echo "          cache: $CACHE_MGR"
echo "          cache-dependency-path: $CACHE_DEP_PATH"
fi)
$CI_STEPS
CI_EOF
      ;;

    python)
      cat > .github/workflows/ci.yml << 'CI_EOF'
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
CI_EOF
      # Append dynamic parts
      if [[ -f "pyproject.toml" ]]; then
        echo "      - run: pip install -e ." >> .github/workflows/ci.yml
      else
        echo "      - run: pip install -r requirements.txt" >> .github/workflows/ci.yml
      fi
      echo "      - run: ruff check ." >> .github/workflows/ci.yml
      cat >> .github/workflows/ci.yml << 'CI_EOF'
      - name: Run tests
        run: pytest
        continue-on-error: true
CI_EOF
      ;;

    go)
      cat > .github/workflows/ci.yml << 'CI_EOF'
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go mod download
      - run: go vet ./...
      - run: go build ./...
      - name: Run tests
        run: go test ./...
        continue-on-error: true
CI_EOF
      ;;

    rust)
      cat > .github/workflows/ci.yml << 'CI_EOF'
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy -- -D warnings
      - run: cargo build
      - name: Run tests
        run: cargo test
        continue-on-error: true
CI_EOF
      ;;
  esac

  echo "Created .github/workflows/ci.yml"
fi
# ─── Append agent instructions to CLAUDE.md ──────────────────────────
if [[ ! -f "CLAUDE.md" ]]; then
  echo "# $REPO_NAME" > CLAUDE.md
  echo "" >> CLAUDE.md
  echo "Created CLAUDE.md"
else
  echo "" >> CLAUDE.md
  echo "Appending agent instructions to existing CLAUDE.md"
fi

# Idempotent: skip if already appended
if grep -q "## Autonomous Loop Rules" CLAUDE.md 2>/dev/null; then
  echo "Agent instructions already present in CLAUDE.md, skipping"
else
  cat >> CLAUDE.md << CLAUDE_EOF

# $REPO_NAME — Agent Instructions

## Project
$(if [[ "$LANG_TYPE" == "node" && -n "$PKG_DIR" ]]; then
  echo "Node.js project. Package directory: \`$PKG_DIR/\`. Source: \`$SRC_DIR/\`. Package manager: \`$PKG_MGR\`."
elif [[ "$LANG_TYPE" == "python" ]]; then
  echo "Python project. Source: \`$SRC_DIR/\`."
elif [[ "$LANG_TYPE" == "go" ]]; then
  echo "Go project. Module: \`go.mod\`."
elif [[ "$LANG_TYPE" == "rust" ]]; then
  echo "Rust project. Source: \`$SRC_DIR/\`. Manifest: \`Cargo.toml\`."
else
  echo "Project detected at \`$REPO_ROOT\`."
fi)

## Commands
$(if [[ -n "$INSTALL_CMD" ]]; then echo "- Install: \`$INSTALL_CMD\`"; fi)
$(if [[ -n "$LINT_CMD" ]]; then echo "- Lint: \`$LINT_CMD\`"; fi)
$(if [[ -n "$BUILD_CMD" ]]; then echo "- Build: \`$BUILD_CMD\`"; fi)
$(if [[ -n "$TEST_CMD" ]]; then echo "- Test: \`$TEST_CMD\`"; fi)
$(if [[ -z "$INSTALL_CMD" && -z "$LINT_CMD" && -z "$BUILD_CMD" && -z "$TEST_CMD" ]]; then echo "No standard commands detected. Configure manually if needed."; fi)

## Git Conventions
- Conventional commits: \`feat:\`, \`fix:\`, \`chore:\`, \`test:\`, \`refactor:\`
- Feature branches: \`claude/<description>-<id>\`
- Always push with \`-u origin <branch>\`
- Never force push. Never merge/rebase main without human approval.

## Autonomous Loop Rules
- Use git worktrees for isolation: \`git worktree add /tmp/$REPO_NAME-<task> -b claude/<task>-<id>\`
- After every change: run lint > build > test (if available) > only commit if all pass
- One logical change per commit. Keep changes narrow and independent.
- If 3+ consecutive failures on the same issue, stop and report.
- Clean up worktrees when done: \`git worktree remove /tmp/$REPO_NAME-<task>\`
- **Maintenance dedup** (Lint Guardian, Build Watchdog only): before creating a new lint-fix or build-fix branch, check if an identical open PR already exists. If so, skip. Issue branches are always unique.

## Epic / Project Branch Rules
- If an issue describes a **large project** with multiple sub-tasks, create a parent epic branch: \`claude/epic-<name>\`
- Sub-task branches are created from the epic branch (not main): \`git worktree add /tmp/$REPO_NAME-<subtask> -b claude/<subtask> claude/epic-<name>\`
- Sub-task PRs target the epic branch as base (not main)
- When all sub-tasks are merged into the epic branch, create a single PR from epic branch > main for human review

## Agent Backlog Convention
$(if [[ "$MODEL_MODE" == "dual" ]]; then
cat << 'DUAL_BACKLOG'
- **GitHub Issues** with label `claude-ready` are the primary work queue.
- The **Triage Worker** automatically classifies issues as `claude-sonnet` or `claude-opus`.
- Skip triage by labeling issues `claude-sonnet` or `claude-opus` directly.
- Claim issues by: removing the routing label, adding `claude-wip`, self-assigning.
DUAL_BACKLOG
else
cat << 'SINGLE_BACKLOG'
- **GitHub Issues** with label `claude-ready` are the work queue.
- Claim issues by: removing `claude-ready`, adding `claude-wip`, self-assigning.
SINGLE_BACKLOG
fi)
- When done: create a PR with "Closes #N" in the body, comment on the issue with PR link, remove \`claude-wip\`.
- If blocked: add \`claude-blocked\` label, comment explaining the problem.
- **Inline TODOs**: \`// TODO(@claude): <description>\` in source files are micro-tasks.
- Regular \`// TODO:\` comments (without @claude) are NOT agent work items — leave them alone.
- When completing an inline TODO(@claude): remove the comment entirely after implementing.
- One item per iteration. Never pick up multiple items at once.
$(if [[ "$MODEL_MODE" == "dual" ]]; then
cat << DUAL_ROUTING

## Model Routing
- Issues labeled \`claude-sonnet\` are handled by the Sonnet session (fast, cheap). Issues labeled \`claude-opus\` are handled by the Opus session (powerful, thorough).
- The **Triage Worker** (runs on Sonnet) classifies incoming \`claude-ready\` issues automatically:
  - **Sonnet tasks**: typo fixes, copy changes, simple bug fixes with clear steps, dependency bumps, config tweaks, lint/style fixes, adding tests for existing code, small UI changes, one-file changes
  - **Opus tasks**: new features requiring multi-file changes, architectural decisions, complex refactors, epic/project issues with sub-tasks, performance optimization, security fixes, anything requiring deep codebase understanding
- If unsure, default to \`claude-opus\`.
- Inline \`// TODO(@claude):\` micro-tasks default to Sonnet unless the comment indicates complexity.
- Maintenance loops (Lint Guardian, Build Watchdog) always run on Sonnet.
- Code Quality Sweep always runs on Opus.
DUAL_ROUTING
fi)

## MCP-First Rule
- **Always use available MCP tools directly** instead of generating scripts for the human to run.
- If you have mcp__supabase__execute_sql, run the SQL yourself — do not write a .sql file and say "go run this".
- If you have mcp__github__create_pull_request, create the PR yourself — do not tell the human to do it.
- The human should only be involved for decisions and approvals, never for executing steps the agent can do itself.
- Check your available tools before suggesting manual steps. If a tool exists for the action, use it.

## Verify Chain
Run this after every change before committing:
\`\`\`
${VERIFY_CHAIN:-# no verify commands detected — configure lint/build/test for your project}
\`\`\`

## Code Patterns
$(case "$LANG_TYPE" in
  node)
    echo "- Source directory: \`$SRC_DIR/\`"
    [[ -d "$SRC_DIR/lib" ]] && echo "- Shared utilities: \`$SRC_DIR/lib/\`"
    [[ -d "$SRC_DIR/components" ]] && echo "- Components: \`$SRC_DIR/components/\`"
    [[ -d "$SRC_DIR/app" ]] && echo "- App Router pages: \`$SRC_DIR/app/\`"
    [[ -d "$SRC_DIR/pages" ]] && echo "- Pages: \`$SRC_DIR/pages/\`"
    [[ -f "$SRC_DIR/lib/types.ts" ]] && echo "- Types: \`$SRC_DIR/lib/types.ts\`"
    ;;
  python)
    echo "- Source directory: \`$SRC_DIR/\`"
    [[ -d "tests" ]] && echo "- Tests: \`tests/\`"
    [[ -f "pyproject.toml" ]] && echo "- Config: \`pyproject.toml\`"
    ;;
  go)
    echo "- Source: \`./\` (Go modules)"
    echo "- Tests: \`*_test.go\` files alongside source"
    echo "- Config: \`go.mod\`"
    ;;
  rust)
    echo "- Source: \`src/\`"
    echo "- Tests: \`tests/\` directory and inline \`#[cfg(test)]\`"
    echo "- Config: \`Cargo.toml\`"
    ;;
  *)
    echo "- Source detected at \`$REPO_ROOT\`"
    echo "- Configure source paths, lint, build, and test commands for your project"
    ;;
esac)
CLAUDE_EOF
  echo "Appended agent instructions to CLAUDE.md"
fi
# ─── Generate LOOPS.md ────────────────────────────────────────────────

# Count loops
if [[ "$MODEL_MODE" == "dual" ]]; then
  SONNET_COUNT=3  # triage + sonnet-todo + pr-responder
  [[ -n "$LINT_CMD" ]] && SONNET_COUNT=$((SONNET_COUNT + 1))
  [[ -n "$BUILD_CMD" ]] && SONNET_COUNT=$((SONNET_COUNT + 1))
  OPUS_COUNT=2  # opus-todo + quality-sweep
  TOTAL_COUNT=$((SONNET_COUNT + OPUS_COUNT))
else
  LOOP_COUNT=3  # todo-worker + pr-responder + quality-sweep
  [[ -n "$LINT_CMD" ]] && LOOP_COUNT=$((LOOP_COUNT + 1))
  [[ -n "$BUILD_CMD" ]] && LOOP_COUNT=$((LOOP_COUNT + 1))
  TOTAL_COUNT=$LOOP_COUNT
fi

# ── Header ──
if [[ "$MODEL_MODE" == "dual" ]]; then
  cat > LOOPS.md << LOOPS_EOF
# $REPO_NAME — Autonomous Loops

Generated by \`claude-agent-bootstrap/setup.sh\` v3 for **${GITHUB_USER}/${GITHUB_REPO}**.
Config: dual model, $LOOP_SPEED speed, $LANG_TYPE project.

## Quick Start

\`\`\`bash
./start-loops.sh          # start both sessions ($TOTAL_COUNT loops)
./start-loops.sh sonnet   # start only Sonnet ($SONNET_COUNT loops)
./start-loops.sh opus     # start only Opus ($OPUS_COUNT loops)
./start-loops.sh stop     # kill both sessions
\`\`\`

Monitor: \`tmux attach -t claude-sonnet\` / \`tmux attach -t claude-opus\`

## Model Routing

This setup uses **two Claude Code sessions** running in parallel — one with Sonnet (fast/cheap)
for straightforward work, and one with Opus (powerful) for complex tasks.

| Session | Model | Loops |
|---------|-------|-------|
| **Sonnet** | claude-sonnet-4-6 | Triage Worker, Sonnet TODO Worker$(if [[ -n "$LINT_CMD" ]]; then echo ", Lint Guardian"; fi)$(if [[ -n "$BUILD_CMD" ]]; then echo ", Build Watchdog"; fi), PR Comment Responder |
| **Opus** | claude-opus-4-6 | Opus TODO Worker, Code Quality Sweep |

**How it works:**
1. You file an issue with \`claude-ready\` label
2. The **Triage Worker** (Sonnet) classifies it as \`claude-sonnet\` or \`claude-opus\`
3. The appropriate TODO Worker picks it up
4. Skip triage by labeling \`claude-sonnet\` or \`claude-opus\` directly
LOOPS_EOF
else
  cat > LOOPS.md << LOOPS_EOF
# $REPO_NAME — Autonomous Loops

Generated by \`claude-agent-bootstrap/setup.sh\` v3 for **${GITHUB_USER}/${GITHUB_REPO}**.
Config: $MODEL_MODE, $LOOP_SPEED speed, $LANG_TYPE project.

## Quick Start

\`\`\`bash
./start-loops.sh          # start session ($TOTAL_COUNT loops)
./start-loops.sh stop     # kill session
\`\`\`

Monitor: \`tmux attach -t claude-agent\`
LOOPS_EOF
fi

# ── Prerequisites ──
cat >> LOOPS.md << 'PREREQ_EOF'

## Prerequisites

Before starting the loops, ensure:

1. **Claude Code CLI** installed (`claude` command available)
2. **GitHub MCP server** configured:
   ```
   claude mcp add github -- npx -y @modelcontextprotocol/server-github
   export GITHUB_PERSONAL_ACCESS_TOKEN=ghp_...
   ```
3. **tmux** installed (optional — enables `./start-loops.sh` automation)
4. **GitHub labels** created (see Label Setup one-shot below, or create manually)
PREREQ_EOF

# ── One-Shot Setup ──
cat >> LOOPS.md << 'ONESHOT_HEADER'

---

## One-Shot Setup (run these first, once)

Paste these one at a time in a Claude Code session before starting the recurring loops.
ONESHOT_HEADER

# Label setup one-shot (if AUTO_LABELS)
if [[ "$AUTO_LABELS" == "true" ]]; then
  if [[ "$MODEL_MODE" == "dual" ]]; then
    cat >> LOOPS.md << LABEL_EOF

### Label Setup
\`\`\`
You are a Label Setup helper for ${GITHUB_USER}/${GITHUB_REPO}. Create the following GitHub labels. For each label, use mcp__github__get_label to check if it exists first — skip if it does. Create missing labels using the GitHub API via available MCP tools.

Labels to create:
- claude-ready (color: 0E8A16, description: "Add to issues for agent triage")
- claude-sonnet (color: 1D76DB, description: "Simple tasks for Sonnet session")
- claude-opus (color: 5319E7, description: "Complex tasks for Opus session")
- claude-wip (color: FBCA04, description: "Agent is working on this")
- claude-blocked (color: D93F0B, description: "Agent is stuck, needs human help")

Report which labels were created and which already existed.
\`\`\`
LABEL_EOF
  else
    cat >> LOOPS.md << LABEL_EOF

### Label Setup
\`\`\`
You are a Label Setup helper for ${GITHUB_USER}/${GITHUB_REPO}. Create the following GitHub labels. For each label, use mcp__github__get_label to check if it exists first — skip if it does. Create missing labels using the GitHub API via available MCP tools.

Labels to create:
- claude-ready (color: 0E8A16, description: "Add to issues for agent pickup")
- claude-wip (color: FBCA04, description: "Agent is working on this")
- claude-blocked (color: D93F0B, description: "Agent is stuck, needs human help")

Report which labels were created and which already existed.
\`\`\`
LABEL_EOF
  fi
fi

# Language-specific one-shots
case "$LANG_TYPE" in
  node)
    cat >> LOOPS.md << ONESHOT_EOF

### Test Bootstrapper
\`\`\`
You are a Test Bootstrapper for ${GITHUB_USER}/${GITHUB_REPO}. This is a one-shot task:
1) Create a worktree from origin/main: git worktree add /tmp/${GITHUB_REPO}-test-bootstrap -b claude/add-test-infra main
2) cd into the worktree's package dir ($PKG_DIR)
3) Install test dependencies: $PKG_MGR install -D vitest @vitejs/plugin-react @testing-library/react @testing-library/jest-dom jsdom
4) Create vitest.config.ts with: react plugin, jsdom environment, setupFiles pointing to test-setup.ts, path alias @ -> ./src
5) Create ${SRC_DIR:-src}/test-setup.ts with: import "@testing-library/jest-dom/vitest"
6) Write initial tests for any utility functions found in ${SRC_DIR:-src}/lib/ and at least one component test
7) Run: ${VERIFY_CHAIN:-$PKG_MGR run lint && $PKG_MGR run build && npx vitest run}
8) If all green: commit "chore: add vitest test infrastructure with initial tests", push -u origin claude/add-test-infra
9) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: claude/add-test-infra, base: main)
10) Clean up worktree: git worktree remove /tmp/${GITHUB_REPO}-test-bootstrap
\`\`\`

### Type Strictifier
\`\`\`
You are a Type Strictifier for ${GITHUB_USER}/${GITHUB_REPO}. This is a one-shot task:
1) Create a worktree from origin/main: git worktree add /tmp/${GITHUB_REPO}-type-strict -b claude/remove-any-types main
2) Search all .ts and .tsx files in ${SRC_DIR:-src}/ for explicit \`any\` types (grep for ": any" and "<any>" and "as any")
3) Replace each \`any\` with the correct specific type. Use \`unknown\` only when the type genuinely cannot be determined.
4) Run: ${VERIFY_CHAIN:-$PKG_MGR run lint && $PKG_MGR run build && npx vitest run}
5) If all green: commit "fix: replace any types with strict alternatives", push -u origin claude/remove-any-types
6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: claude/remove-any-types, base: main)
7) Clean up worktree: git worktree remove /tmp/${GITHUB_REPO}-type-strict
\`\`\`
ONESHOT_EOF
    ;;

  python)
    cat >> LOOPS.md << ONESHOT_EOF

### Test Bootstrapper
\`\`\`
You are a Test Bootstrapper for ${GITHUB_USER}/${GITHUB_REPO}. This is a one-shot task:
1) Create a worktree from origin/main: git worktree add /tmp/${GITHUB_REPO}-test-bootstrap -b claude/add-test-infra main
2) cd into the worktree
3) Install: ${INSTALL_CMD} && pip install pytest pytest-cov
4) Create conftest.py in tests/ with basic fixtures
5) Write initial tests for core modules found in ${SRC_DIR}/
6) Run: ${VERIFY_CHAIN:-ruff check . && pytest}
7) If all green: commit "chore: add pytest infrastructure with initial tests", push -u origin claude/add-test-infra
8) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: claude/add-test-infra, base: main)
9) Clean up worktree: git worktree remove /tmp/${GITHUB_REPO}-test-bootstrap
\`\`\`

### Type Hints Strictifier
\`\`\`
You are a Type Hints Strictifier for ${GITHUB_USER}/${GITHUB_REPO}. This is a one-shot task:
1) Create a worktree from origin/main: git worktree add /tmp/${GITHUB_REPO}-type-strict -b claude/add-type-hints main
2) Search all .py files in ${SRC_DIR}/ for functions missing type hints
3) Add type hints to all function parameters and return types. Use specific types, not Any.
4) Run: ${VERIFY_CHAIN:-ruff check . && pytest}
5) If all green: commit "fix: add comprehensive type hints", push -u origin claude/add-type-hints
6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: claude/add-type-hints, base: main)
7) Clean up worktree: git worktree remove /tmp/${GITHUB_REPO}-type-strict
\`\`\`
ONESHOT_EOF
    ;;

  go)
    cat >> LOOPS.md << ONESHOT_EOF

### Test Bootstrapper
\`\`\`
You are a Test Bootstrapper for ${GITHUB_USER}/${GITHUB_REPO}. This is a one-shot task:
1) Create a worktree from origin/main: git worktree add /tmp/${GITHUB_REPO}-test-bootstrap -b claude/add-tests main
2) cd into the worktree
3) Identify key packages with no or minimal test coverage
4) Write table-driven tests following Go testing conventions
5) Run: ${VERIFY_CHAIN:-go vet ./... && go build ./... && go test ./...}
6) If all green: commit "chore: add table-driven tests for core packages", push -u origin claude/add-tests
7) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: claude/add-tests, base: main)
8) Clean up worktree: git worktree remove /tmp/${GITHUB_REPO}-test-bootstrap
\`\`\`

### Linter Setup
\`\`\`
You are a Linter Setup helper for ${GITHUB_USER}/${GITHUB_REPO}. This is a one-shot task:
1) Create a worktree from origin/main: git worktree add /tmp/${GITHUB_REPO}-linter -b claude/add-golangci-lint main
2) Create .golangci.yml with sensible defaults (govet, errcheck, staticcheck, unused, gosimple)
3) Run golangci-lint run ./... and fix any issues found
4) Run: ${VERIFY_CHAIN:-go vet ./... && go build ./... && go test ./...}
5) If all green: commit "chore: add golangci-lint configuration", push -u origin claude/add-golangci-lint
6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: claude/add-golangci-lint, base: main)
7) Clean up worktree: git worktree remove /tmp/${GITHUB_REPO}-linter
\`\`\`
ONESHOT_EOF
    ;;

  rust)
    cat >> LOOPS.md << ONESHOT_EOF

### Test Bootstrapper
\`\`\`
You are a Test Bootstrapper for ${GITHUB_USER}/${GITHUB_REPO}. This is a one-shot task:
1) Create a worktree from origin/main: git worktree add /tmp/${GITHUB_REPO}-test-bootstrap -b claude/add-tests main
2) cd into the worktree
3) Identify modules with no or minimal test coverage
4) Add unit tests using #[cfg(test)] modules and integration tests in tests/
5) Run: ${VERIFY_CHAIN:-cargo clippy && cargo build && cargo test}
6) If all green: commit "chore: add comprehensive test coverage", push -u origin claude/add-tests
7) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: claude/add-tests, base: main)
8) Clean up worktree: git worktree remove /tmp/${GITHUB_REPO}-test-bootstrap
\`\`\`

### Clippy Strict Mode
\`\`\`
You are a Clippy Setup helper for ${GITHUB_USER}/${GITHUB_REPO}. This is a one-shot task:
1) Create a worktree from origin/main: git worktree add /tmp/${GITHUB_REPO}-clippy -b claude/strict-clippy main
2) Add clippy configuration to Cargo.toml or clippy.toml with stricter lints
3) Run cargo clippy -- -D warnings and fix all warnings
4) Run: ${VERIFY_CHAIN:-cargo clippy && cargo build && cargo test}
5) If all green: commit "chore: enable strict clippy lints", push -u origin claude/strict-clippy
6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: claude/strict-clippy, base: main)
7) Clean up worktree: git worktree remove /tmp/${GITHUB_REPO}-clippy
\`\`\`
ONESHOT_EOF
    ;;

  generic)
    cat >> LOOPS.md << 'ONESHOT_EOF'

> No language-specific one-shot tasks for generic projects. Configure your build tools,
> then add test bootstrapper and linter setup tasks manually.
ONESHOT_EOF
    ;;
esac
# ── Loop prompt documentation in LOOPS.md ──

cat >> LOOPS.md << 'SEPARATOR'

---
SEPARATOR

if [[ "$MODEL_MODE" == "dual" ]]; then
  # ── Session 1: Sonnet ──
  cat >> LOOPS.md << LOOPS_EOF

## Session 1: Sonnet (fast/cheap) — \`claude --model claude-sonnet-4-6\`

Paste all $SONNET_COUNT of these into a Sonnet session:

### Triage Worker
\`\`\`
/loop $TRIAGE_INTERVAL You are a Triage Worker loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) Check GitHub Issues labeled \`claude-ready\` using mcp__github__list_issues (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, labels: ["claude-ready"]). 2) If none found, stop. 3) For each \`claude-ready\` issue (max 5 per iteration), read the title and body and assess complexity: SONNET tasks = typo fixes, copy/text changes, simple bug fixes with clear reproduction steps, dependency bumps, config/env tweaks, lint/style fixes, adding tests for existing code, small UI changes (color, spacing, text), single-file changes, documentation updates, adding error messages, renaming variables/functions. OPUS tasks = new features requiring 3+ file changes, architectural decisions or restructuring, complex refactors spanning multiple modules, epic/project issues with sub-tasks, performance optimization requiring profiling, security fixes, database schema changes, API design, anything requiring deep codebase understanding or creative problem-solving, issues where the approach is ambiguous. 4) Relabel the issue: remove \`claude-ready\`, add \`claude-sonnet\` or \`claude-opus\` via mcp__github__issue_write. 5) Add a brief comment explaining the classification via mcp__github__add_issue_comment. 6) If unsure, default to \`claude-opus\`. 7) Never pick up work yourself — only classify and route.
\`\`\`

### Sonnet TODO Worker
\`\`\`
/loop $WORKER_INTERVAL You are a Sonnet TODO Worker loop for ${GITHUB_USER}/${GITHUB_REPO}. You handle SIMPLE tasks only. On each iteration: 1) Check GitHub Issues labeled \`claude-sonnet\` using mcp__github__list_issues (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, labels: ["claude-sonnet"]). 2) ALSO check issues labeled \`claude-wip\` that were originally \`claude-sonnet\` for new user comments — use mcp__github__issue_read with method "get_comments". 3) Scan for inline \`// TODO(@claude):\` comments in ${SRC_DIR:-src}/ — these default to Sonnet unless the comment indicates complex work. 4) If nothing found, stop. 5) Pick ONE item (prefer issues over TODOs). 6) For issues: relabel claude-sonnet>claude-wip via mcp__github__issue_write. 7) Check if the issue is a sub-task of a larger epic. If yes: create worktree from the epic branch, PR against that branch. If no: create worktree from origin/main, PR against main. 8) Implement the change, run ${VERIFY_CHAIN:-tests}, commit+push. 9) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: epic-branch-or-main). 10) Comment on the issue with the PR link via mcp__github__add_issue_comment. 11) Clean up worktree. If stuck after 3 attempts: add \`claude-blocked\` label and comment "Blocked — may need opus-level reasoning. Consider relabeling to claude-opus." 12) For inline TODOs: same flow — implement, remove the comment, commit+push, create PR. 13) For wip issues with new user comments: incorporate feedback. 14) IMPORTANT: Always use available MCP tools directly. One item per iteration. Never force push.
\`\`\`
LOOPS_EOF

  # Lint Guardian (conditional)
  if [[ -n "$LINT_CMD" ]]; then
    cat >> LOOPS.md << LOOPS_EOF

### Lint Guardian
\`\`\`
/loop $MAINTENANCE_INTERVAL You are a Lint Guardian loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already an open PR with "lint" in the title that YOU created via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If an unmerged lint-fix PR exists, skip. 2) Create worktree from origin/main. 3) ${INSTALL_CMD:+$INSTALL_CMD && }${LINT_FIX_CMD}. 4) If no file changes (git diff --stat is empty), clean up and stop. 5) If changes: commit "fix: auto-fix lint violations", verify ${VERIFY_CHAIN:-lint+build+test pass}, push branch. 6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main). 7) Clean up worktree. Never force push.
\`\`\`
LOOPS_EOF
  fi

  # Build Watchdog (conditional)
  if [[ -n "$BUILD_CMD" ]]; then
    cat >> LOOPS.md << LOOPS_EOF

### Build Watchdog
\`\`\`
/loop $MAINTENANCE_INTERVAL You are a Build Watchdog loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already an open PR with "build" or "type error" in the title that YOU created via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If an unmerged build-fix PR exists, skip. 2) Create worktree from origin/main. 3) ${INSTALL_CMD:+$INSTALL_CMD && }${BUILD_CMD}. 4) If build succeeds with zero errors, clean up and stop. 5) If errors: fix them, verify ${VERIFY_CHAIN:-lint+build+test}, commit+push. 6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main). 7) Clean up worktree. If stuck after 3 attempts, stop and report. Never force push.
\`\`\`
LOOPS_EOF
  fi

  # PR Comment Responder (always, dual mode with escalation)
  cat >> LOOPS.md << LOOPS_EOF

### PR Comment Responder
\`\`\`
/loop $RESPONDER_INTERVAL You are a PR Comment Responder loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) List open PRs via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}). 2) Check BOTH inline review comments (get_review_comments) AND general PR comments (get_comments) via mcp__github__pull_request_read. 3) Filter for actionable requests — skip approvals, acks, bot messages. If none, stop. 4) Assess each comment's complexity: if the requested change is a simple fix (typo, rename, small tweak), handle it. If the comment requests a complex rework, reply acknowledging and add label \`claude-opus\` to the PR for escalation to the Opus session. 5) For changes you handle (max 3): create worktree from PR branch, make the change, verify ${VERIFY_CHAIN:-lint+build+test}, commit+push to the PR branch. 6) Reply to comments: "Addressed in latest commit." 7) If the comment asks you to run something and you have an MCP tool for it, execute it directly. 8) Clean up worktree. Never force push.
\`\`\`

---

## Session 2: Opus (powerful) — \`claude --model claude-opus-4-6\`

Paste both of these into an Opus session:

### Opus TODO Worker
\`\`\`
/loop $WORKER_INTERVAL You are an Opus TODO Worker loop for ${GITHUB_USER}/${GITHUB_REPO}. You handle COMPLEX tasks that require deep reasoning. On each iteration: 1) Check GitHub Issues labeled \`claude-opus\` using mcp__github__list_issues (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, labels: ["claude-opus"]). 2) ALSO check issues labeled \`claude-wip\` that were originally \`claude-opus\` for new user comments. 3) ALSO check open PRs labeled \`claude-opus\` (escalated from PR Comment Responder) via mcp__github__list_pull_requests. 4) If nothing found, stop. 5) Pick ONE item (prefer escalated PRs > issues > inline TODOs). 6) For issues: relabel claude-opus>claude-wip via mcp__github__issue_write. 7) Check if the issue is an epic. If yes: create epic branch, break down into sub-issues. 8) For regular issues: create worktree from origin/main (or epic branch), implement, run ${VERIFY_CHAIN:-tests}, commit+push. 9) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: epic-branch-or-main). 10) For escalated PRs: create worktree from PR branch, address complex review feedback, commit+push. 11) Clean up worktree. If stuck after 3 attempts: add \`claude-blocked\` label. 12) IMPORTANT: Always use available MCP tools directly. One item per iteration. Never force push.
\`\`\`

### Code Quality Sweep
\`\`\`
/loop $SWEEP_INTERVAL You are a Code Quality Sweep loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already 3+ open PRs with "refactor:" or "quality" in the title via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If so, skip. 2) Create worktree from origin/main. 3) Search for: TODO/FIXME/HACK comments (not @claude), unused exports, functions >80 lines, duplicated code blocks. 4) Fix exactly ONE issue. 5) Verify ${VERIFY_CHAIN:-lint+build+test}. 6) Commit+push. 7) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main) with title "refactor: <summary>". 8) Clean up worktree. If nothing found, stop. One issue per iteration. Never force push.
\`\`\`
LOOPS_EOF

else
  # ── Single model session ──
  cat >> LOOPS.md << LOOPS_EOF

## Session: ${SINGLE_MODEL_NAME} — \`claude --model ${SINGLE_MODEL}\`

Paste all $TOTAL_COUNT of these into a ${SINGLE_MODEL_NAME} session:

### TODO Worker
\`\`\`
/loop $WORKER_INTERVAL You are a TODO Worker loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) Check GitHub Issues labeled \`claude-ready\` using mcp__github__list_issues (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, labels: ["claude-ready"]). 2) ALSO check issues labeled \`claude-wip\` for new user comments — use mcp__github__issue_read with method "get_comments". 3) Scan for inline \`// TODO(@claude):\` comments in ${SRC_DIR:-src}/ — these are micro-tasks. 4) If nothing found, stop. 5) Pick ONE item (prefer issues over TODOs). 6) For issues: relabel claude-ready>claude-wip via mcp__github__issue_write. 7) Check if the issue is a sub-task of a larger epic. If yes: create worktree from the epic branch, PR against that branch. If no: create worktree from origin/main, PR against main. 8) Check if the issue is an epic. If yes: create epic branch, break down into sub-issues. 9) Implement the change, run ${VERIFY_CHAIN:-tests}, commit+push. 10) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: epic-branch-or-main). 11) Comment on the issue with the PR link via mcp__github__add_issue_comment. 12) Clean up worktree. If stuck after 3 attempts: add \`claude-blocked\` label. 13) For inline TODOs: same flow — implement, remove the comment, commit+push, create PR. 14) IMPORTANT: Always use available MCP tools directly. One item per iteration. Never force push.
\`\`\`
LOOPS_EOF

  # Lint Guardian (conditional)
  if [[ -n "$LINT_CMD" ]]; then
    cat >> LOOPS.md << LOOPS_EOF

### Lint Guardian
\`\`\`
/loop $MAINTENANCE_INTERVAL You are a Lint Guardian loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already an open PR with "lint" in the title that YOU created via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If an unmerged lint-fix PR exists, skip. 2) Create worktree from origin/main. 3) ${INSTALL_CMD:+$INSTALL_CMD && }${LINT_FIX_CMD}. 4) If no file changes (git diff --stat is empty), clean up and stop. 5) If changes: commit "fix: auto-fix lint violations", verify ${VERIFY_CHAIN:-lint+build+test pass}, push branch. 6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main). 7) Clean up worktree. Never force push.
\`\`\`
LOOPS_EOF
  fi

  # Build Watchdog (conditional)
  if [[ -n "$BUILD_CMD" ]]; then
    cat >> LOOPS.md << LOOPS_EOF

### Build Watchdog
\`\`\`
/loop $MAINTENANCE_INTERVAL You are a Build Watchdog loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already an open PR with "build" or "type error" in the title that YOU created via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If an unmerged build-fix PR exists, skip. 2) Create worktree from origin/main. 3) ${INSTALL_CMD:+$INSTALL_CMD && }${BUILD_CMD}. 4) If build succeeds with zero errors, clean up and stop. 5) If errors: fix them, verify ${VERIFY_CHAIN:-lint+build+test}, commit+push. 6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main). 7) Clean up worktree. If stuck after 3 attempts, stop and report. Never force push.
\`\`\`
LOOPS_EOF
  fi

  # PR Comment Responder (single mode — no escalation)
  cat >> LOOPS.md << LOOPS_EOF

### PR Comment Responder
\`\`\`
/loop $RESPONDER_INTERVAL You are a PR Comment Responder loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) List open PRs via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}). 2) Check BOTH inline review comments (get_review_comments) AND general PR comments (get_comments) via mcp__github__pull_request_read. 3) Filter for actionable requests — skip approvals, acks, bot messages. If none, stop. 4) For changes you can handle (max 3): create worktree from PR branch, make the change, verify ${VERIFY_CHAIN:-lint+build+test}, commit+push to the PR branch. 5) Reply to comments: "Addressed in latest commit." 6) If the comment asks you to run something and you have an MCP tool for it, execute it directly. 7) If truly stuck after 3 attempts, add \`claude-blocked\` label to the PR and reply explaining the difficulty. 8) Clean up worktree. Never force push.
\`\`\`

### Code Quality Sweep
\`\`\`
/loop $SWEEP_INTERVAL You are a Code Quality Sweep loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already 3+ open PRs with "refactor:" or "quality" in the title via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If so, skip. 2) Create worktree from origin/main. 3) Search for: TODO/FIXME/HACK comments (not @claude), unused exports, functions >80 lines, duplicated code blocks. 4) Fix exactly ONE issue. 5) Verify ${VERIFY_CHAIN:-lint+build+test}. 6) Commit+push. 7) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main) with title "refactor: <summary>". 8) Clean up worktree. If nothing found, stop. One issue per iteration. Never force push.
\`\`\`
LOOPS_EOF
fi
# ── Labels, Filing Work, After 3 Days ──

cat >> LOOPS.md << 'SEPARATOR'

---
SEPARATOR

if [[ "$MODEL_MODE" == "dual" ]]; then
  cat >> LOOPS.md << LOOPS_EOF

## Labels Required

Create these on your GitHub repo (or use the Label Setup one-shot above):
- \`claude-ready\` — add to any issue for agent pickup (Triage Worker will classify)
- \`claude-sonnet\` — simple tasks routed to Sonnet session
- \`claude-opus\` — complex tasks routed to Opus session
- \`claude-wip\` — agent adds when claiming
- \`claude-blocked\` — agent adds if stuck

**Shortcut:** Skip triage by labeling issues \`claude-sonnet\` or \`claude-opus\` directly.

## Filing Work

**GitHub Issues** (features, bugs):
\`\`\`
Title: feat: add dark mode toggle
Labels: claude-ready     (or claude-sonnet / claude-opus if you know the complexity)
Body: Add a dark mode toggle to the navbar. Store preference in localStorage.
\`\`\`

**Epic / project issues** (multi-step features — always Opus):
\`\`\`
Title: Plan: add multi-county support
Labels: claude-opus      (epics always go to Opus — skip triage)
Body: Plan and implement multi-county support. Break this into sub-tasks.
\`\`\`

**Inline micro-tasks** (default to Sonnet):
\`\`\`
// TODO(@claude): memoize this expensive filter
// TODO(@claude): add aria-label to this button
\`\`\`
LOOPS_EOF
else
  cat >> LOOPS.md << LOOPS_EOF

## Labels Required

Create these on your GitHub repo (or use the Label Setup one-shot above):
- \`claude-ready\` — add to any issue for agent pickup
- \`claude-wip\` — agent adds when claiming
- \`claude-blocked\` — agent adds if stuck

## Filing Work

**GitHub Issues** (features, bugs):
\`\`\`
Title: feat: add dark mode toggle
Labels: claude-ready
Body: Add a dark mode toggle to the navbar. Store preference in localStorage.
\`\`\`

**Epic / project issues** (multi-step features):
\`\`\`
Title: Plan: add multi-county support
Labels: claude-ready
Body: Plan and implement multi-county support. Break this into sub-tasks.
\`\`\`

**Inline micro-tasks:**
\`\`\`
// TODO(@claude): memoize this expensive filter
// TODO(@claude): add aria-label to this button
\`\`\`
LOOPS_EOF
fi

# After 3 Days section
if [[ "$MODEL_MODE" == "dual" ]]; then
  cat >> LOOPS.md << LOOPS_EOF

## After the Initial 3-Day Period

When your loop sessions expire (Claude Code sessions last ~3 days max):

### 1. Review what was accomplished
\`\`\`
Review the state of ${GITHUB_USER}/${GITHUB_REPO} after the bootstrap period:
1) List all open PRs via mcp__github__list_pull_requests — how many need merge/close?
2) List issues still labeled claude-wip or claude-blocked — any stuck work?
3) Count branches: git branch | grep claude/ | wc -l
4) Run the verify chain: ${VERIFY_CHAIN:-echo "no verify chain configured"}
5) Summarize: PRs to merge, issues to close, branches to prune.
\`\`\`

### 2. Clean up stale branches
\`\`\`
Clean up stale agent branches in ${GITHUB_USER}/${GITHUB_REPO}:
1) List local branches matching claude/*: git branch | grep claude/
2) For each: check if it has a merged/closed PR. If yes, delete: git branch -d claude/<name>
3) Prune remote tracking refs: git fetch --prune
4) Remove orphaned worktrees: git worktree prune
5) Report how many branches were cleaned up.
\`\`\`

### 3. Restart
\`\`\`bash
./start-loops.sh stop   # kill expired sessions
./start-loops.sh        # restart both
\`\`\`

Or restart one at a time:
\`\`\`bash
./start-loops.sh sonnet   # $SONNET_COUNT loops
./start-loops.sh opus     # $OPUS_COUNT loops
\`\`\`

To adjust loop intervals, edit prompt files in \`.claude/loops/\` and restart.
LOOPS_EOF
else
  cat >> LOOPS.md << LOOPS_EOF

## After the Initial 3-Day Period

When your loop session expires (Claude Code sessions last ~3 days max):

### 1. Review what was accomplished
\`\`\`
Review the state of ${GITHUB_USER}/${GITHUB_REPO} after the bootstrap period:
1) List all open PRs via mcp__github__list_pull_requests — how many need merge/close?
2) List issues still labeled claude-wip or claude-blocked — any stuck work?
3) Count branches: git branch | grep claude/ | wc -l
4) Run the verify chain: ${VERIFY_CHAIN:-echo "no verify chain configured"}
5) Summarize: PRs to merge, issues to close, branches to prune.
\`\`\`

### 2. Clean up stale branches
\`\`\`
Clean up stale agent branches in ${GITHUB_USER}/${GITHUB_REPO}:
1) List local branches matching claude/*: git branch | grep claude/
2) For each: check if it has a merged/closed PR. If yes, delete: git branch -d claude/<name>
3) Prune remote tracking refs: git fetch --prune
4) Remove orphaned worktrees: git worktree prune
5) Report how many branches were cleaned up.
\`\`\`

### 3. Restart
\`\`\`bash
./start-loops.sh stop   # kill expired session
./start-loops.sh        # restart ($TOTAL_COUNT loops)
\`\`\`

To adjust loop intervals, edit prompt files in \`.claude/loops/\` and restart.
LOOPS_EOF
fi

echo "Created LOOPS.md"
# ─── Write individual loop prompt files ───────────────────────────────
mkdir -p .claude/loops
# Clean old loop files to avoid stale prompts from a different model mode
rm -f .claude/loops/*.txt

if [[ "$MODEL_MODE" == "dual" ]]; then
  # ── Dual mode: 5-7 files (01-05 sonnet, 06-07 opus) ──

  cat > .claude/loops/01-triage.txt << PROMPT_EOF
/loop $TRIAGE_INTERVAL You are a Triage Worker loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) Check GitHub Issues labeled \`claude-ready\` using mcp__github__list_issues (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, labels: ["claude-ready"]). 2) If none found, stop. 3) For each \`claude-ready\` issue (max 5 per iteration), read the title and body and assess complexity: SONNET tasks = typo fixes, copy/text changes, simple bug fixes with clear reproduction steps, dependency bumps, config/env tweaks, lint/style fixes, adding tests for existing code, small UI changes (color, spacing, text), single-file changes, documentation updates, adding error messages, renaming variables/functions. OPUS tasks = new features requiring 3+ file changes, architectural decisions or restructuring, complex refactors spanning multiple modules, epic/project issues with sub-tasks, performance optimization requiring profiling, security fixes, database schema changes, API design, anything requiring deep codebase understanding or creative problem-solving, issues where the approach is ambiguous. 4) Relabel the issue: remove \`claude-ready\`, add \`claude-sonnet\` or \`claude-opus\` via mcp__github__issue_write. 5) Add a brief comment explaining the classification via mcp__github__add_issue_comment, e.g. "Triaged as sonnet-level: single-file config change" or "Triaged as opus-level: multi-file feature requiring new component architecture". 6) If unsure, default to \`claude-opus\` — better to over-qualify than under-deliver. 7) Never pick up work yourself — only classify and route.
PROMPT_EOF

  cat > .claude/loops/02-sonnet-todo.txt << PROMPT_EOF
/loop $WORKER_INTERVAL You are a Sonnet TODO Worker loop for ${GITHUB_USER}/${GITHUB_REPO}. You handle SIMPLE tasks only. On each iteration: 1) Check GitHub Issues labeled \`claude-sonnet\` using mcp__github__list_issues (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, labels: ["claude-sonnet"]). 2) ALSO check issues labeled \`claude-wip\` that were originally \`claude-sonnet\` for new user comments — use mcp__github__issue_read with method "get_comments" to see if the user has replied with decisions, approvals, or feedback. 3) Scan for inline \`// TODO(@claude):\` comments in ${SRC_DIR:-src}/ — these default to Sonnet unless the comment indicates complex work. 4) If nothing found and no new user comments on wip issues, stop. 5) Pick ONE item (prefer issues over TODOs). 6) For issues: relabel claude-sonnet>claude-wip via mcp__github__issue_write. 7) Check if the issue is a sub-task of a larger epic. If yes: create worktree from the epic branch (claude/epic-<name>), PR against that branch. If no: create worktree from origin/main, PR against main. 8) Implement the change, run ${VERIFY_CHAIN:-tests}, commit+push. 9) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: epic-branch-or-main) with title from the issue and body that says "Closes #N" plus a summary. 10) Comment on the issue with the PR link via mcp__github__add_issue_comment. 11) Clean up worktree. If stuck after 3 attempts: add \`claude-blocked\` label and add comment "Blocked — may need opus-level reasoning. Consider relabeling to claude-opus." 12) For inline TODOs: same flow — implement, remove the comment, commit+push, create PR. 13) For wip issues with new user comments: incorporate feedback, reply acknowledging. 14) IMPORTANT: Always use available MCP tools directly. One item per iteration. Never force push.
PROMPT_EOF

  if [[ -n "$LINT_CMD" ]]; then
    cat > .claude/loops/03-lint-guardian.txt << PROMPT_EOF
/loop $MAINTENANCE_INTERVAL You are a Lint Guardian loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already an open PR with "lint" in the title that YOU created (author is the bot) via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If an unmerged lint-fix PR already exists, skip this iteration — wait for it to be merged. 2) Create worktree from origin/main. 3) ${INSTALL_CMD:+$INSTALL_CMD && }${LINT_FIX_CMD}. 4) If no file changes (git diff --stat is empty), clean up and stop — lint is clean. 5) If changes: commit "fix: auto-fix lint violations", verify ${VERIFY_CHAIN:-lint+build+test pass}, push branch. 6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main) with title "fix: auto-fix lint violations" and body summarizing what was fixed. 7) Clean up worktree. Never force push.
PROMPT_EOF
  fi

  if [[ -n "$BUILD_CMD" ]]; then
    cat > .claude/loops/04-build-watchdog.txt << PROMPT_EOF
/loop $MAINTENANCE_INTERVAL You are a Build Watchdog loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already an open PR with "build" or "type error" in the title that YOU created via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If an unmerged build-fix PR already exists, skip this iteration — wait for it to be merged. 2) Create worktree from origin/main. 3) ${INSTALL_CMD:+$INSTALL_CMD && }${BUILD_CMD}. 4) If build succeeds with zero errors, clean up and stop — build is green. 5) If type errors or compilation failures: fix them, verify ${VERIFY_CHAIN:-lint+build+test}, commit+push. 6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main) with title "fix: resolve build errors" and body describing what was fixed. 7) Clean up worktree. If stuck after 3 attempts, stop and report. Never force push.
PROMPT_EOF
  fi

  cat > .claude/loops/05-pr-responder.txt << PROMPT_EOF
/loop $RESPONDER_INTERVAL You are a PR Comment Responder loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) List open PRs via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}). 2) Check BOTH inline review comments (get_review_comments) AND general PR comments (get_comments) via mcp__github__pull_request_read. 3) Filter for actionable requests — skip approvals, acks, bot messages. If none, stop. 4) Assess each comment's complexity: if the requested change is a simple fix (typo, rename, small tweak, adding a check), handle it. If the comment requests a complex rework (redesign component, rethink approach, add substantial new logic), reply acknowledging and add a comment: "This requires deeper changes — escalating to opus session" and add label \`claude-opus\` to the PR. 5) For changes you handle (max 3): create worktree from PR branch, make the requested change, verify ${VERIFY_CHAIN:-lint+build+test}, commit+push to the PR branch. 6) For inline comments: reply via mcp__github__add_reply_to_pull_request_comment. For general comments: reply via mcp__github__add_issue_comment. Body: "Addressed in latest commit." 7) If the comment asks you to run something (SQL, deploy, etc.) and you have an MCP tool for it, execute it directly. 8) Clean up worktree. Never force push.
PROMPT_EOF

  cat > .claude/loops/06-opus-todo.txt << PROMPT_EOF
/loop $WORKER_INTERVAL You are an Opus TODO Worker loop for ${GITHUB_USER}/${GITHUB_REPO}. You handle COMPLEX tasks that require deep reasoning. On each iteration: 1) Check GitHub Issues labeled \`claude-opus\` using mcp__github__list_issues (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, labels: ["claude-opus"]). 2) ALSO check issues labeled \`claude-wip\` that were originally \`claude-opus\` for new user comments — use mcp__github__issue_read with method "get_comments". 3) ALSO check open PRs labeled \`claude-opus\` (escalated from Sonnet PR Comment Responder) via mcp__github__list_pull_requests — these are PRs needing complex rework based on review feedback. 4) If nothing found, stop. 5) Pick ONE item (prefer escalated PRs > issues > inline TODOs). 6) For issues: relabel claude-opus>claude-wip via mcp__github__issue_write. 7) Check if the issue is an epic (describes a large project with sub-tasks). If yes: create the epic branch \`claude/epic-<name>\`, break down into sub-issues (label each \`claude-opus\` or \`claude-sonnet\` based on sub-task complexity), and create them via mcp__github__issue_write. 8) For regular issues: check if it's a sub-task of a larger epic. If yes: create worktree from the epic branch, PR against that branch. If no: create worktree from origin/main, PR against main. 9) Implement the change, run ${VERIFY_CHAIN:-tests}, commit+push. 10) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: epic-branch-or-main) with title from the issue and body that says "Closes #N" plus a thorough summary of the approach and changes. 11) Comment on the issue with the PR link via mcp__github__add_issue_comment. 12) For escalated PRs: create worktree from the PR branch, address the complex review feedback, verify, commit+push, reply to the comments. 13) Clean up worktree. If stuck after 3 attempts: add \`claude-blocked\` label. 14) IMPORTANT: Always use available MCP tools directly. One item per iteration. Never force push.
PROMPT_EOF

  cat > .claude/loops/07-quality-sweep.txt << PROMPT_EOF
/loop $SWEEP_INTERVAL You are a Code Quality Sweep loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already an open PR with "refactor:" or "quality" in the title via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If 3+ quality PRs are open, skip this iteration — let the human merge before creating more. 2) Create worktree from origin/main. 3) Search for: TODO/FIXME/HACK comments (not @claude), unused exports, functions >80 lines, duplicated code blocks. 4) Fix exactly ONE issue. 5) Verify ${VERIFY_CHAIN:-lint+build+test}. 6) Commit+push. 7) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main) with title "refactor: <summary>" and body describing the quality issue fixed. 8) Clean up worktree. 9) If nothing found, stop — codebase is clean. One issue per iteration. Max 2 files per commit. Never force push.
PROMPT_EOF

  LOOP_FILE_COUNT=5
  [[ -n "$LINT_CMD" ]] && LOOP_FILE_COUNT=$((LOOP_FILE_COUNT + 1))
  [[ -n "$BUILD_CMD" ]] && LOOP_FILE_COUNT=$((LOOP_FILE_COUNT + 1))
  echo "Created .claude/loops/ ($LOOP_FILE_COUNT prompt files, dual mode)"

else
  # ── Single mode: 3-5 files ──

  cat > .claude/loops/01-todo-worker.txt << PROMPT_EOF
/loop $WORKER_INTERVAL You are a TODO Worker loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) Check GitHub Issues labeled \`claude-ready\` using mcp__github__list_issues (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, labels: ["claude-ready"]). 2) ALSO check issues labeled \`claude-wip\` for new user comments — use mcp__github__issue_read with method "get_comments" to see if the user has replied with decisions, approvals, or feedback. 3) Scan for inline \`// TODO(@claude):\` comments in ${SRC_DIR:-src}/ — these are micro-tasks. 4) If nothing found and no new user comments on wip issues, stop. 5) Pick ONE item (prefer issues over TODOs). 6) For issues: relabel claude-ready>claude-wip via mcp__github__issue_write. 7) Check if the issue is an epic (describes a large project with sub-tasks). If yes: create the epic branch \`claude/epic-<name>\`, break down into sub-issues, create them via mcp__github__issue_write. 8) For regular issues: check if it's a sub-task of a larger epic. If yes: create worktree from the epic branch, PR against that branch. If no: create worktree from origin/main, PR against main. 9) Implement the change, run ${VERIFY_CHAIN:-tests}, commit+push. 10) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: epic-branch-or-main) with title from the issue and body that says "Closes #N" plus a summary. 11) Comment on the issue with the PR link via mcp__github__add_issue_comment. 12) Clean up worktree. If stuck after 3 attempts: add \`claude-blocked\` label. 13) For inline TODOs: same flow — implement, remove the comment, commit+push, create PR. 14) For wip issues with new user comments: incorporate feedback, reply acknowledging. 15) IMPORTANT: Always use available MCP tools directly. One item per iteration. Never force push.
PROMPT_EOF

  if [[ -n "$LINT_CMD" ]]; then
    cat > .claude/loops/02-lint-guardian.txt << PROMPT_EOF
/loop $MAINTENANCE_INTERVAL You are a Lint Guardian loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already an open PR with "lint" in the title that YOU created (author is the bot) via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If an unmerged lint-fix PR already exists, skip this iteration — wait for it to be merged. 2) Create worktree from origin/main. 3) ${INSTALL_CMD:+$INSTALL_CMD && }${LINT_FIX_CMD}. 4) If no file changes (git diff --stat is empty), clean up and stop — lint is clean. 5) If changes: commit "fix: auto-fix lint violations", verify ${VERIFY_CHAIN:-lint+build+test pass}, push branch. 6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main) with title "fix: auto-fix lint violations" and body summarizing what was fixed. 7) Clean up worktree. Never force push.
PROMPT_EOF
  fi

  if [[ -n "$BUILD_CMD" ]]; then
    cat > .claude/loops/03-build-watchdog.txt << PROMPT_EOF
/loop $MAINTENANCE_INTERVAL You are a Build Watchdog loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already an open PR with "build" or "type error" in the title that YOU created via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If an unmerged build-fix PR already exists, skip this iteration — wait for it to be merged. 2) Create worktree from origin/main. 3) ${INSTALL_CMD:+$INSTALL_CMD && }${BUILD_CMD}. 4) If build succeeds with zero errors, clean up and stop — build is green. 5) If type errors or compilation failures: fix them, verify ${VERIFY_CHAIN:-lint+build+test}, commit+push. 6) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main) with title "fix: resolve build errors" and body describing what was fixed. 7) Clean up worktree. If stuck after 3 attempts, stop and report. Never force push.
PROMPT_EOF
  fi

  cat > .claude/loops/04-pr-responder.txt << PROMPT_EOF
/loop $RESPONDER_INTERVAL You are a PR Comment Responder loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) List open PRs via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}). 2) Check BOTH inline review comments (get_review_comments) AND general PR comments (get_comments) via mcp__github__pull_request_read. 3) Filter for actionable requests — skip approvals, acks, bot messages. If none, stop. 4) For changes you can handle (max 3): create worktree from PR branch, make the requested change, verify ${VERIFY_CHAIN:-lint+build+test}, commit+push to the PR branch. 5) For inline comments: reply via mcp__github__add_reply_to_pull_request_comment. For general comments: reply via mcp__github__add_issue_comment. Body: "Addressed in latest commit." 6) If the comment asks you to run something (SQL, deploy, etc.) and you have an MCP tool for it, execute it directly. 7) If truly stuck after 3 attempts on a comment, add \`claude-blocked\` label to the PR and reply explaining the difficulty. 8) Clean up worktree. Never force push.
PROMPT_EOF

  cat > .claude/loops/05-quality-sweep.txt << PROMPT_EOF
/loop $SWEEP_INTERVAL You are a Code Quality Sweep loop for ${GITHUB_USER}/${GITHUB_REPO}. On each iteration: 1) FIRST check if there's already an open PR with "refactor:" or "quality" in the title via mcp__github__list_pull_requests (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, state: open). If 3+ quality PRs are open, skip this iteration — let the human merge before creating more. 2) Create worktree from origin/main. 3) Search for: TODO/FIXME/HACK comments (not @claude), unused exports, functions >80 lines, duplicated code blocks. 4) Fix exactly ONE issue. 5) Verify ${VERIFY_CHAIN:-lint+build+test}. 6) Commit+push. 7) Create a PR via mcp__github__create_pull_request (owner: ${GITHUB_USER}, repo: ${GITHUB_REPO}, head: branch, base: main) with title "refactor: <summary>" and body describing the quality issue fixed. 8) Clean up worktree. 9) If nothing found, stop — codebase is clean. One issue per iteration. Max 2 files per commit. Never force push.
PROMPT_EOF

  LOOP_FILE_COUNT=3
  [[ -n "$LINT_CMD" ]] && LOOP_FILE_COUNT=$((LOOP_FILE_COUNT + 1))
  [[ -n "$BUILD_CMD" ]] && LOOP_FILE_COUNT=$((LOOP_FILE_COUNT + 1))
  echo "Created .claude/loops/ ($LOOP_FILE_COUNT prompt files, single mode)"
fi
# ─── Generate start-loops.sh ──────────────────────────────────────────

if [[ "$MODEL_MODE" == "dual" ]]; then
  cat > start-loops.sh << 'STARTLOOPS_EOF'
#!/usr/bin/env bash
#
# Start the Claude agent fleet — two tmux sessions, 7 loops total.
# Usage: ./start-loops.sh          (start both sessions)
#        ./start-loops.sh sonnet   (start only Sonnet session)
#        ./start-loops.sh opus     (start only Opus session)
#        ./start-loops.sh stop     (kill both sessions)
#        ./start-loops.sh --dry-run (print prompts without starting)
#
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

SONNET_SESSION="claude-sonnet"
OPUS_SESSION="claude-opus"
LOOP_DIR=".claude/loops"

# --- Dry-run mode ---
if [[ "${1:-}" == "--dry-run" ]]; then
  echo "Loop prompts that would be started:"
  echo ""
  echo "═══ Sonnet Session (claude-sonnet-4-6) ═══"
  for f in "$LOOP_DIR"/0{1,2,3,4,5}-*.txt; do
    [[ -f "$f" ]] || continue
    echo "── $(basename "$f") ──"
    cat "$f"
    echo ""
  done
  echo "═══ Opus Session (claude-opus-4-6) ═══"
  for f in "$LOOP_DIR"/0{6,7}-*.txt; do
    [[ -f "$f" ]] || continue
    echo "── $(basename "$f") ──"
    cat "$f"
    echo ""
  done
  exit 0
fi

# --- Preflight checks ---
if ! command -v claude &>/dev/null; then
  echo "ERROR: claude CLI not found in PATH"
  exit 1
fi

if [[ ! -d "$LOOP_DIR" ]]; then
  echo "ERROR: $LOOP_DIR not found. Run setup.sh first."
  exit 1
fi

# --- tmux optional ---
if ! command -v tmux &>/dev/null; then
  echo "tmux not found. Manual instructions:"
  echo ""
  echo "  Start two Claude Code sessions in separate terminals:"
  echo ""
  echo "  Terminal 1 (Sonnet): claude --model claude-sonnet-4-6"
  echo "  Then paste prompts from:"
  for f in "$LOOP_DIR"/0{1,2,3,4,5}-*.txt; do
    [[ -f "$f" ]] && echo "    - $f"
  done
  echo ""
  echo "  Terminal 2 (Opus): claude --model claude-opus-4-6"
  echo "  Then paste prompts from:"
  for f in "$LOOP_DIR"/0{6,7}-*.txt; do
    [[ -f "$f" ]] && echo "    - $f"
  done
  echo ""
  echo "  Install tmux to enable automatic startup:"
  echo "    sudo apt install tmux   (Debian/Ubuntu)"
  echo "    brew install tmux       (macOS)"
  exit 0
fi

# --- Helper: send a prompt file to a tmux session ---
send_loop() {
  local session="$1"
  local file="$2"
  local name
  name=$(basename "$file" .txt)

  tmux load-buffer -b loop-cmd "$file"
  tmux paste-buffer -b loop-cmd -t "$session"
  tmux send-keys -t "$session" Enter
  echo "   + $name"
  sleep 3
}

# --- Stop command ---
if [[ "${1:-}" == "stop" ]]; then
  echo "Stopping agent sessions..."
  tmux kill-session -t "$SONNET_SESSION" 2>/dev/null && echo "  Killed $SONNET_SESSION" || echo "  $SONNET_SESSION not running"
  tmux kill-session -t "$OPUS_SESSION" 2>/dev/null && echo "  Killed $OPUS_SESSION" || echo "  $OPUS_SESSION not running"
  exit 0
fi

# --- Start Sonnet session ---
start_sonnet() {
  if tmux has-session -t "$SONNET_SESSION" 2>/dev/null; then
    echo "Session '$SONNET_SESSION' already running. Kill it first: ./start-loops.sh stop"
    return 1
  fi

  echo "Starting Sonnet session ($SONNET_SESSION)..."
  tmux new-session -d -s "$SONNET_SESSION" "claude --model claude-sonnet-4-6"
  echo "  Waiting for Claude to start..."
  sleep 8

  for f in "$LOOP_DIR"/0{1,2,3,4,5}-*.txt; do
    [[ -f "$f" ]] && send_loop "$SONNET_SESSION" "$f"
  done

  local count=0
  for f in "$LOOP_DIR"/0{1,2,3,4,5}-*.txt; do [[ -f "$f" ]] && count=$((count + 1)); done
  echo "Sonnet session running with $count loops"
  echo "  Attach: tmux attach -t $SONNET_SESSION"
}

# --- Start Opus session ---
start_opus() {
  if tmux has-session -t "$OPUS_SESSION" 2>/dev/null; then
    echo "Session '$OPUS_SESSION' already running. Kill it first: ./start-loops.sh stop"
    return 1
  fi

  echo "Starting Opus session ($OPUS_SESSION)..."
  tmux new-session -d -s "$OPUS_SESSION" "claude --model claude-opus-4-6"
  echo "  Waiting for Claude to start..."
  sleep 8

  for f in "$LOOP_DIR"/0{6,7}-*.txt; do
    [[ -f "$f" ]] && send_loop "$OPUS_SESSION" "$f"
  done

  local count=0
  for f in "$LOOP_DIR"/0{6,7}-*.txt; do [[ -f "$f" ]] && count=$((count + 1)); done
  echo "Opus session running with $count loops"
  echo "  Attach: tmux attach -t $OPUS_SESSION"
}

# --- Main ---
case "${1:-all}" in
  sonnet) start_sonnet ;;
  opus)   start_opus ;;
  all)
    start_sonnet
    echo ""
    start_opus
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Agent fleet running"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "  Sonnet: tmux attach -t $SONNET_SESSION"
    echo "  Opus:   tmux attach -t $OPUS_SESSION"
    echo "  Stop:   ./start-loops.sh stop"
    echo ""
    ;;
  *)
    echo "Usage: ./start-loops.sh [sonnet|opus|stop|--dry-run|all]"
    exit 1
    ;;
esac
STARTLOOPS_EOF

else
  # Single model mode — use expanding heredoc to embed model name
  cat > start-loops.sh << STARTLOOPS_EOF
#!/usr/bin/env bash
#
# Start the Claude agent fleet — one tmux session.
# Usage: ./start-loops.sh          (start session)
#        ./start-loops.sh stop     (kill session)
#        ./start-loops.sh --dry-run (print prompts without starting)
#
set -euo pipefail

REPO_ROOT="\$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "\$REPO_ROOT"

SESSION="claude-agent"
MODEL="$SINGLE_MODEL"
LOOP_DIR=".claude/loops"

# --- Dry-run mode ---
if [[ "\${1:-}" == "--dry-run" ]]; then
  echo "Loop prompts that would be started (\$MODEL):"
  echo ""
  for f in "\$LOOP_DIR"/*.txt; do
    [[ -f "\$f" ]] || continue
    echo "── \$(basename "\$f") ──"
    cat "\$f"
    echo ""
  done
  exit 0
fi

# --- Preflight checks ---
if ! command -v claude &>/dev/null; then
  echo "ERROR: claude CLI not found in PATH"
  exit 1
fi

if [[ ! -d "\$LOOP_DIR" ]]; then
  echo "ERROR: \$LOOP_DIR not found. Run setup.sh first."
  exit 1
fi

# --- tmux optional ---
if ! command -v tmux &>/dev/null; then
  echo "tmux not found. Manual instructions:"
  echo ""
  echo "  Start a Claude Code session:"
  echo "    claude --model \$MODEL"
  echo ""
  echo "  Then paste prompts from these files one at a time:"
  for f in "\$LOOP_DIR"/*.txt; do
    [[ -f "\$f" ]] && echo "    - \$f"
  done
  echo ""
  echo "  Install tmux to enable automatic startup:"
  echo "    sudo apt install tmux   (Debian/Ubuntu)"
  echo "    brew install tmux       (macOS)"
  exit 0
fi

# --- Helper: send a prompt file to a tmux session ---
send_loop() {
  local session="\$1"
  local file="\$2"
  local name
  name=\$(basename "\$file" .txt)

  tmux load-buffer -b loop-cmd "\$file"
  tmux paste-buffer -b loop-cmd -t "\$session"
  tmux send-keys -t "\$session" Enter
  echo "   + \$name"
  sleep 3
}

# --- Stop command ---
if [[ "\${1:-}" == "stop" ]]; then
  echo "Stopping agent session..."
  tmux kill-session -t "\$SESSION" 2>/dev/null && echo "  Killed \$SESSION" || echo "  \$SESSION not running"
  exit 0
fi

# --- Start session ---
if tmux has-session -t "\$SESSION" 2>/dev/null; then
  echo "Session '\$SESSION' already running. Kill it first: ./start-loops.sh stop"
  exit 1
fi

echo "Starting ${SINGLE_MODEL_NAME} session (\$SESSION)..."
tmux new-session -d -s "\$SESSION" "claude --model \$MODEL"
echo "  Waiting for Claude to start..."
sleep 8

count=0
for f in "\$LOOP_DIR"/*.txt; do
  [[ -f "\$f" ]] && send_loop "\$SESSION" "\$f" && count=\$((count + 1))
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Agent fleet running: \$count loops"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Attach: tmux attach -t \$SESSION"
echo "  Stop:   ./start-loops.sh stop"
echo ""
STARTLOOPS_EOF
fi

chmod +x start-loops.sh
echo "Created start-loops.sh"
# ─── Summary ──────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Bootstrap complete for $REPO_NAME"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Generated:"
echo "  .claude/settings.json     (permissions)"
echo "  .claude/bootstrap.conf    (saved config)"
echo "  .claude/loops/*.txt       (loop prompts)"
echo "  CLAUDE.md                 (agent instructions)"
echo "  LOOPS.md                  (documentation)"
echo "  start-loops.sh            (tmux launcher)"
if [[ "$LANG_TYPE" != "generic" ]] && [[ -f ".github/workflows/ci.yml" ]]; then
echo "  .github/workflows/ci.yml  (CI pipeline)"
fi
echo ""
echo "Next steps:"
if [[ "$AUTO_LABELS" == "true" ]]; then
echo "  1. Run the Label Setup one-shot from LOOPS.md"
else
if [[ "$MODEL_MODE" == "dual" ]]; then
echo "  1. Create GitHub labels: claude-ready, claude-sonnet, claude-opus, claude-wip, claude-blocked"
else
echo "  1. Create GitHub labels: claude-ready, claude-wip, claude-blocked"
fi
fi
echo "  2. Commit generated files"
if [[ "$LANG_TYPE" != "generic" ]]; then
echo "  3. Run one-shot tasks from LOOPS.md (Test Bootstrapper, etc.)"
echo "  4. Start the agent fleet:"
else
echo "  3. Start the agent fleet:"
fi
echo ""
if [[ "$MODEL_MODE" == "dual" ]]; then
echo "     ./start-loops.sh          # start both sessions"
echo "     ./start-loops.sh sonnet   # Sonnet only"
echo "     ./start-loops.sh opus     # Opus only"
echo "     ./start-loops.sh stop     # kill all"
else
echo "     ./start-loops.sh          # start session"
echo "     ./start-loops.sh stop     # kill session"
fi
echo ""
echo "  See LOOPS.md for full documentation."
echo ""
